### ISSUE TITLE
Create GitHub actions to test any code before merging

### ISSUE THREAD

**Issue by upkarlidder** [Call-for-Code-for-Racial-Justice/Incident-Accuracy-Reporting-System#61]
### Background on the problem the feature will solve/improved user experience
Add GitHub Actions to test and build new code pushed to a branch or committed to a pull request. Code that passes all the steps in the GitHub action can be merged in the repository.

### Describe the solution you'd like
A GitHub action runs whenever code is committed to any branch or PR is made to the main branch for each of the following components:
- [ ] main repo
- [ ] frontend

Refer to a similar action that was implemented for the[ UI folder in Five Fifths Voter project.](https://github.com/Call-for-Code-for-Racial-Justice/Five-Fifths-Voter/issues/232)

Each action will 
- [ ] install dependencies 
- [ ] build for production 
- [ ] run all tests
- [ ] linting with [prettier](https://prettier.io/docs/en/index.html). Discuss with the team on what linter to use.

### Tasks
- [ ] Ensure install, build and lint steps run locally on your system
- [ ] Read more about [GitHub actions](https://docs.github.com/en/actions/learn-github-actions) 
- [ ] Create an action for each folder. You can read more [JavaScript build actions here](https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs-or-python).
- [ ] Commit and push your GitHub action code.
- [ ] Go to the [Actions tab](https://github.com/Call-for-Code-for-Racial-Justice/Incident-Accuracy-Reporting-System/actions) to see if it worked.

### Acceptance Criteria 
GitHub action runs for every new code commit and PR.

FYI @demilolu

**Comment by sadiejay** [comment]
Wow Thanks! I'm interested where can I learn more about this?

**Comment by sadiejay** [comment]
Hi, I have a question about the node.js version used? This is my first time building a github actions bot and I've been comparing with the listed reference. 

The [package.json](https://github.com/Call-for-Code-for-Racial-Justice/Five-Fifths-Voter/blob/main/ui/package.json) file of the [UI folder github action bot](https://github.com/Call-for-Code-for-Racial-Justice/Five-Fifths-Voter/blob/main/.github/workflows/build-ui.yml) reference shows an "engines" object. It seems the github action relates to that node version for the bot setup step. However github says ["If you don't specify a Node.js version, GitHub uses the environment's default Node.js version."](https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs-or-python#specifying-the-node.js-version)

However, I don't see something like that listed in this [project's frontend package.json](https://github.com/Call-for-Code-for-Racial-Justice/Incident-Accuracy-Reporting-System/blob/main/frontend/package.json). 

I'm submitting my pull request so so we can see my first shot. Any advice would be helpful!

This has been a fun challenge so far :)

**Comment by demilolu** [comment]
following up here.
